Update g.raphael.js - add semicolon
In my company we are merging several files into one. g.raphael.js comes immediately before g.line.js. Trying to evaluate the resulting file shows "TypeError: object is not a function because first code line of g.line.js starts with "(". So the browser (at least current Chrome) tries to evaluate that together showing an error (of course). We did a monkey patch using ";" at the end of g.raphael.js (which anyway makes sense) and do not experience problems any more.

Cheers,
Tobias Krogh